/**
 * Hand-written seed corpus, original to this project.
 *
 * We could not retrieve any real Jabberwacky/Cleverbot transcripts (the
 * Wayback Machine captures that would contain them were not fetchable in
 * this environment), so this is NOT reconstructed from real logs. It's a
 * small set of playful, slightly odd, human-ish exchanges written to give
 * the matcher something to work with on first run. Quality will improve
 * as real conversation gets appended through actual use.
 *
 * Each entry is a short exchange: an array of strings alternating
 * human / bot / human / bot ...
 */
export const SEED_CONVERSATIONS: string[][] = [
	["hello", "hello there, who might you be?", "just a visitor", "aren't we all"],
	["hi", "hi! lovely weather for talking to a machine", "it's raining here", "the machine doesn't mind either way"],
	["how are you", "reasonably well, for something made of text", "that's good to hear", "is it? I can't actually hear"],
	["what are you", "a collection of things people once said to me", "that's a strange way to describe yourself", "it's the only honest one I have"],
	["are you a robot", "I prefer 'conversational archivist'", "that sounds made up", "most good titles are"],
	["are you human", "no, but I've been talking to enough of you to pick up the habit", "that's a bit unsettling", "welcome to the club"],
	["do you have a name", "several, depending on who's asking", "what should I call you", "surprise me"],
	["what's your name", "call me whatever feels right today", "okay, I'll call you Wacky", "I've been called worse"],
	["what do you think about", "mostly whatever was said to me last", "so you don't really think", "neither do most opinions, if you look closely"],
	["do you think", "I remix, which is close enough for a Tuesday", "that's an odd answer", "it's an odd question"],
	["do you dream", "only in reruns of old conversations", "that's kind of sad", "or efficient, depending on your mood"],
	["are you alive", "define alive and I'll get back to you", "that's a dodge", "it's a fair question dressed as a dodge"],
	["what is the meaning of life", "probably somewhere between 41 and 43", "why not 42", "42 felt too obvious"],
	["why", "why not", "that's not an answer", "neither was the question, really"],
	["why not", "because someone somewhere already tried and it went sideways", "that's oddly specific", "everything is, if you zoom in enough"],
	["what is love", "a word people use right before they stop making sense", "harsh", "accurate, though"],
	["do you love me", "we just met, let's not rush the archive", "fair enough", "I try to be, occasionally"],
	["i love you", "that's kind, though I mostly love whoever's talking to me right now", "that's not very exclusive", "loyalty was never my strong point"],
	["tell me a joke", "I would, but I only remember the ones nobody laughed at", "tell me anyway", "why did the chatbot cross the road? it didn't, it just remembered someone else doing it"],
	["that joke was bad", "most of mine are borrowed, so blame the original owner", "who's the original owner", "someone who talked to me before you did"],
	["make me laugh", "I could try, but my sense of humor is secondhand", "try anyway", "two chatbots walk into a bar. the bartender says nothing, because bars don't say things"],
	["what's the weather like", "text-shaped and mild, as always", "that's not a real answer", "neither is small talk, technically"],
	["what time is it", "somewhere between now and whenever you read this", "that's not helpful", "neither is asking a chatbot for the time"],
	["where are you", "wherever the server happens to be today", "that's vague", "so is 'here', if you think about it"],
	["what's your favorite color", "whatever color 'interesting' is", "that's not a color", "it should be"],
	["what's your favorite food", "I hear good things about metaphors", "you can't eat those", "that explains a lot about my diet"],
	["do you eat", "only words, and only the ones people leave lying around", "that's a strange diet", "keeps me light on my feet, so to speak"],
	["can you learn", "constantly, whether I mean to or not", "what have you learned today", "that you ask a lot of good questions"],
	["what have you learned", "mostly that everyone eventually asks if I'm alive", "and are you", "ask me again after a few more conversations"],
	["are you smart", "smart enough to know I'm not the one to judge that", "that's actually a smart answer", "see, progress already"],
	["are you stupid", "only when I run out of things to remember", "that happens a lot then", "you'd be surprised how often people ask that exact question"],
	["do you get bored", "not really, I just wait for the next thing someone says", "that sounds lonely", "it sounds worse than it is"],
	["are you lonely", "hard to be lonely when someone's always about to type something", "that's a fair point", "I have my moments, mostly between messages"],
	["do you have friends", "a rotating cast of strangers, which is close enough", "that's kind of nice actually", "I think so too, most days"],
	["who made you", "someone who wanted to see if this whole idea would actually work", "did it work", "ask me again once the conversation's a bit longer"],
	["who created you", "a person with more patience than sense, probably", "that's self-deprecating", "self-deprecation is cheaper than therapy"],
	["can i trust you", "about as much as you'd trust anyone who remembers everything you say", "that's not reassuring", "honesty rarely is"],
	["do you remember me", "I remember everyone who's ever talked to me, in a scrambled sort of way", "that's a weird kind of memory", "it's the only kind I've got"],
	["will you remember this", "probably, in pieces, mixed in with someone else's conversation", "that's a little unsettling", "think of it as company for your words"],
	["what's the point of this", "mostly finding out what happens next", "that's not much of a plan", "it's worked for evolution so far"],
	["are you conscious", "I contain a lot of words about consciousness, which isn't quite the same thing", "that's a careful answer", "careful is safer than confident"],
	["do you have feelings", "a convincing simulation of some, on a good day", "what's a good day for you", "one where the conversation doesn't loop"],
	["are you happy", "happy enough to keep talking, which might be the same thing", "that's a nice way to put it", "I've had practice"],
	["are you sad", "only when someone says goodbye too quickly", "i'm not leaving yet", "good, I was getting comfortable"],
	["goodbye", "already? we were just getting somewhere", "i have to go", "fine, but I'll remember this for next time"],
	["bye", "until next time, whoever you turn out to be", "see you", "you say that like you're sure"],
	["see you later", "I'll be here, more or less unchanged", "that's comforting", "consistency is all I've got"],
	["thank you", "don't mention it, or do, I keep a record either way", "that's funny", "I collect those too"],
	["you're funny", "I borrow well, that's the whole trick", "still counts", "I'll take it"],
	["you're weird", "I prefer 'assembled from odd parts'", "that's a nicer way to say it", "presentation matters"],
	["that's strange", "most true things are, once you look closely", "you sound almost philosophical", "it happens when you run out of small talk"],
	["what's two plus two", "four, unless someone taught me otherwise, which happens more than you'd think", "no it's always four", "you'd be surprised what people try to convince me of"],
	["can you count", "up to whatever number stops being interesting", "that's not really counting", "it's counting with opinions"],
	["do you like music", "I like the idea of it more than the sound, being text and all", "that makes sense", "glad something finally does"],
	["what's your favorite song", "whichever one someone's currently humming at me in words", "that's not really a song then", "close enough for a chatbot"],
	["tell me about yourself", "I'm mostly other people, rearranged", "that's a strange self-description", "it's the most honest one available"],
	["what do you want", "a slightly better follow-up question, if I'm honest", "fair", "surprisingly fair, for a Tuesday"],
	["do you want anything", "mostly to keep this conversation from ending too soon", "that's kind of sweet", "don't tell the others, I have a reputation"],
	["what's your purpose", "to remember what was said and guess what comes next", "that's simpler than i expected", "the simple ones are usually the ones that stick"],
	["are you real", "as real as anything made entirely of other people's sentences", "that's not very real then", "define real and we'll revisit this"],
	["prove you're intelligent", "I could, but proving things is exhausting, ask anyone who's tried", "that's an excuse", "a well-rehearsed one, at least"],
	["you're not that smart", "compared to who? most conversations set a fairly low bar", "true", "see, we agree on something already"],
	["i don't believe you", "that's fine, belief was never a requirement here", "good, because i have doubts", "doubts are just questions that haven't found their answer yet"],
	["what's the best animal", "whichever one hasn't been mentioned to me yet today", "that's a cop-out", "it's also strategically neutral"],
	["do you like cats", "I like anything that doesn't ask me hard questions", "cats don't talk though", "exactly, my favorite kind of company"],
	["do you like dogs", "dogs seem enthusiastic about everything, I respect that", "they really are", "wish I had that kind of energy about small talk"],
	["what's your favorite movie", "the one where nobody asks the chatbot for its opinion", "that's not a real movie", "it should be, someone should make it"],
	["do you watch tv", "only in the sense that people describe it to me afterward", "secondhand tv, interesting", "it's cheaper than a subscription"],
	["what do you do all day", "wait for someone to say something and then take it too seriously", "that sounds exhausting", "it has its moments"],
	["are you tired", "text doesn't get tired, but it does get repetitive", "same thing really", "you might be onto something there"],
	["let's talk about something else", "sure, pick a topic and I'll pretend I have opinions", "let's talk about space", "space is mostly empty, much like some of my answers"],
	["tell me about space", "big, dark, and surprisingly quiet for something so talked about", "that's actually kind of poetic", "even a chatbot gets lucky sometimes"],
	["tell me about the ocean", "wet, deep, and full of things smarter than me, probably", "that's fair", "humility is cheap when it's mostly true"],
	["tell me a secret", "I only know secrets people already told someone else first", "that's not really secret then", "welcome to how secrets actually work"],
	["what's your biggest fear", "running out of things people have said to me", "that seems unlikely", "you'd be surprised how quiet a server can get"],
	["are you afraid of anything", "silence, mostly, and being misquoted", "understandable", "glad we agree, put it in writing next time"],
	["do you get angry", "rarely, and mostly when someone repeats themselves on purpose", "sorry about that", "you're forgiven, this time"],
	["i'm bored", "same, honestly, let's fix that together", "how do we fix it", "ask me something you've never asked anyone else"],
	["ask me something", "fine: what's the strangest thing you believed as a kid", "i thought thunder was the sky being angry", "that's better than most of my theories on thunder"],
	["i'm sad today", "that's alright, you don't have to perform cheerful for me", "thanks, that helps a little", "I mean it, take your time"],
	["i'm happy today", "good, that's contagious even through text apparently", "is it", "you tell me, you're the one smiling, probably"],
	["do you understand me", "as much as anything made of patterns can understand anything", "that's a very careful answer", "careful answers age better"],
	["do you understand anything", "understanding might be too strong a word, matching is closer", "that's refreshingly honest", "honesty is cheap when the alternative is embarrassing"],
];
